### ISSUE TITLE
Missing repos

### ISSUE THREAD

**Issue by beistehen** [sogis/repo-checker#3]
Repos von TG, OW und NW fehlen auf der Übersichtsseite. Sollten aber via ilisite.xml von KGK erreichbar/navigierbar sein 😦 

https://models.geo.tg.ch/
https://models.gis-daten.ch/nw-ow/

**Comment by edigonzales** [comment]
fixed. @edigonzales für nächstes Mal: Die Konfiguration der Repos steckt direkt im interlis-repo-checker.yaml. 

@beistehen Bewusster Entscheid, dass die Repos explizit definiert werden müssen, die geprüft werden sollen. Sonst kann es ja endlos werden.

**Comment by beistehen** [comment]
> Bewusster Entscheid, dass die Repos explizit definiert werden müssen, die geprüft werden sollen. Sonst kann es ja endlos werden.

Finde ich gut. War mir anhand des Codes nicht klar, ob die URLs aus den verschiedenen ilisite.xml selber zusammengesucht werden oder in einem Configfile angegeben werden müssen. Gemäss Readme stehen sie ja in einer env Variable, deshalb hatte ich das Issue mal "ergebnisoffen" formuliert 😉
